const HANDLE_INPUT_CHANGE = 1
const SET_LOADING = 2
const SUBMIT_COMPLETE = 3
const FETCH_COMPLETE = 4
const HANDLE_EDIT_BUTTON = 5
const RESET_FORM = 6


export {RESET_FORM,HANDLE_INPUT_CHANGE, SET_LOADING, SUBMIT_COMPLETE, FETCH_COMPLETE, HANDLE_EDIT_BUTTON}